set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER   /tools/xsdk-zynq-edf25.11/sysroots/x86_64-amdedfsdk-linux/usr/bin/aarch64-amd-linux/aarch64-amd-linux-gcc)
set(CMAKE_CXX_COMPILER /tools/xsdk-zynq-edf25.11/sysroots/x86_64-amdedfsdk-linux/usr/bin/aarch64-amd-linux/aarch64-amd-linux-g++)
set(SDK_FLAGS "-mcpu=cortex-a57+crc -mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security")
set(CMAKE_C_FLAGS_INIT   "${SDK_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${SDK_FLAGS}")
set(CMAKE_SYSROOT $ENV{SDKTARGETSYSROOT})
set(CMAKE_FIND_ROOT_PATH $ENV{SDKTARGETSYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
# Qt target side
set(Qt6_DIR $ENV{SDKTARGETSYSROOT}/usr/lib/cmake/Qt6)
set(QT_NO_PACKAGE_VERSION_CHECK TRUE)
set(Qt6_ENABLE_STRICT_PACKAGE_VERSION_CHECK OFF)
# Qt host side (moc, rcc, uic tools)
set(QT_HOST_PATH /usr)
set(QT_HOST_PATH_CMAKE_DIR /usr/lib/x86_64-linux-gnu/cmake)
set(Qt6HostInfo_DIR /usr/lib/x86_64-linux-gnu/cmake/Qt6HostInfo)
set(QT_MOC_EXECUTABLE /usr/lib/qt6/libexec/moc)
set(QT_RCC_EXECUTABLE /usr/lib/qt6/libexec/rcc)
set(QT_UIC_EXECUTABLE /usr/lib/qt6/libexec/uic)
