#include <QFile>
#include <QDebug>
#include <QDir>
#include <cstdio>
#include <cstdlib>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <signal.h>
#include <openssl/evp.h>
#include <openssl/err.h>

// ── AES-256-GCM key (generated by encrypt_script.py) ─────────────────────────
// !! After running encrypt_script.py, paste the new key output here !!

static const unsigned char ENC_KEY[32] = {
    0x9d, 0x8a, 0x99, 0x46, 0xa0, 0x25, 0xb1, 0x2f, 0xaa, 0xc2, 0x18, 0x65, 0x6f, 0xd5, 0xb8, 0x98, 0x1f, 0xdc, 0x5a, 0x96, 0x26, 0xec, 0x65, 0x5c, 0xb7, 0x55, 0x5e, 0x28, 0xb9, 0xd3, 0x5b, 0xa8
};


// ── Global child PID for signal forwarding ───────────────────────────────────
static pid_t g_child_pid = -1;

static void forward_signal(int sig)
{
    if (g_child_pid > 0)
        kill(g_child_pid, sig);
}

static void ensureDir(const char *path)
{
    QDir d(path);
    if (!d.exists()) {
        if (d.mkpath("."))
            qDebug("Created directory: %s", path);
        else
            qWarning("WARNING: Could not create directory: %s", path);
    }
    if (chmod(path, 0700) != 0)
        qWarning("WARNING: chmod 0700 failed for %s", path);
}

// Decrypt AES-256-GCM
// Format: [12-byte nonce][ciphertext][16-byte GCM tag]
static QByteArray decryptScript(const QByteArray &blob)
{
    if (blob.size() < 12 + 16) {
        qCritical("ERROR: Encrypted blob too small");
        return {};
    }

    const unsigned char *nonce      = reinterpret_cast<const unsigned char *>(blob.constData());
    const unsigned char *ciphertext = nonce + 12;
    // GCM tag is the last 16 bytes
    int cipherLen = blob.size() - 12 - 16;
    const unsigned char *tag        = ciphertext + cipherLen;

    if (cipherLen <= 0) {
        qCritical("ERROR: Cipher length is zero or negative");
        return {};
    }

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) { qCritical("ERROR: EVP_CIPHER_CTX_new failed"); return {}; }

    QByteArray plain(cipherLen, 0);
    int outLen = 0, finalLen = 0;

    if (EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), nullptr, nullptr, nullptr) != 1 ||
        EVP_DecryptInit_ex(ctx, nullptr, nullptr, ENC_KEY, nonce)              != 1 ||
        EVP_DecryptUpdate(ctx,
                          reinterpret_cast<unsigned char *>(plain.data()), &outLen,
                          ciphertext, cipherLen)                                             != 1)
    {
        qCritical("ERROR: Decryption failed during update");
        EVP_CIPHER_CTX_free(ctx);
        return {};
    }

    // Set the expected GCM tag
    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, 16,
                        const_cast<unsigned char *>(tag));

    if (EVP_DecryptFinal_ex(ctx,
                            reinterpret_cast<unsigned char *>(plain.data()) + outLen,
                            &finalLen) != 1)
    {
        qCritical("ERROR: GCM tag verification failed — data tampered?");
        EVP_CIPHER_CTX_free(ctx);
        return {};
    }

    EVP_CIPHER_CTX_free(ctx);
    plain.resize(outLen + finalLen);
    qDebug("Decrypted OK — %d bytes", plain.size());
    return plain;
}

int main(int /*argc*/, char ** /*argv*/)
{
    qDebug("=== pyTunning Launcher Starting ===");

    // ── XDG_RUNTIME_DIR ──────────────────────────────────────────────────
    static const char *XDG_DIR = "/run/user/0";
    ensureDir(XDG_DIR);
    setenv("XDG_RUNTIME_DIR", XDG_DIR, 0);

    // ── Wake framebuffer pipeline ─────────────────────────────────────────
    system("echo 'U:1920x1080p-0' > /sys/class/graphics/fb0/mode 2>/dev/null");
    qDebug("Display mode set.");

    // ── Python env ────────────────────────────────────────────────────────
    setenv("PYTHONUNBUFFERED",  "1", 1);
    setenv("PYTHONWARNINGS",    "ignore::DeprecationWarning", 1);

    // ── Load encrypted resource ───────────────────────────────────────────
    QFile src(":/python/tuning_mainwindow.enc");
    if (!src.open(QIODevice::ReadOnly)) {
        qCritical("ERROR: Cannot open resource :/python/tuning_mainwindow.enc");
        return 1;
    }
    QByteArray blob = src.readAll();
    src.close();

    // ── Decrypt in memory ─────────────────────────────────────────────────
    QByteArray script = decryptScript(blob);
    if (script.isEmpty()) {
        fprintf(stderr, "[pyTunning] FATAL: Decryption failed.\n");
        return 1;
    }

    // ── Pipe plaintext directly into python3 stdin (never hits disk) ──────
    int pipeFd[2];
    if (pipe(pipeFd) != 0) {
        perror("[pyTunning] FATAL: pipe() failed");
        return 1;
    }

    pid_t pid = fork();
    if (pid < 0) {
        perror("[pyTunning] FATAL: fork() failed");
        return 1;
    }

    if (pid == 0) {
        // ── Child: become python3 reading from stdin ──────────────────────
        close(pipeFd[1]);                      // close write end
        dup2(pipeFd[0], STDIN_FILENO);         // stdin  = read end
        close(pipeFd[0]);

        char *args[] = { (char *)"python3", (char *)"-", nullptr };
        execvp("python3", args);
        perror("[pyTunning] FATAL: execvp python3 failed");
        _exit(1);
    }

    // ── Parent: store child PID and set up signal forwarding ─────────────
    g_child_pid = pid;
    signal(SIGINT,  forward_signal);   // Ctrl+C  → forward to python3
    signal(SIGTERM, forward_signal);   // kill    → forward to python3
    signal(SIGHUP,  forward_signal);   // hangup  → forward to python3

    // ── Parent: write script into pipe, then close ────────────────────────
    close(pipeFd[0]);                          // close read end

    const char *ptr = script.constData();
    qsizetype   remaining = script.size();

    while (remaining > 0) {
        ssize_t written = write(pipeFd[1], ptr, remaining);
        if (written < 0) {
            perror("[pyTunning] FATAL: write to pipe failed");
            close(pipeFd[1]);
            return 1;
        }
        ptr       += written;
        remaining -= written;
    }
    close(pipeFd[1]);                          // EOF → python3 starts executing

    qDebug("Script piped to python3. Waiting for child...");

    // ── Wait for python3 to finish (keeps terminal attached) ─────────────
    int status = 0;
    waitpid(pid, &status, 0);
    g_child_pid = -1;

    qDebug("python3 exited. Parent exiting.");
    return 0;
}
